# Site settings
title: Betacode
email: hello@betacode.io
description: Official website of betacode.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://betacode.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
sass:
  style: compressed